apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-c4ja
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-c4ja
    app.kubernetes.io/part-of: test-app-nxke
  name: devfile-sample-python-basic-c4ja
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-c4ja
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-c4ja
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-aayy-tenant/test-app-nxke/devfile-sample-python-basic-c4ja@sha256:0b357a145a903dabc387f73dbe0e198cb3f8cc3e25b05123e63aabede7dcaa9d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
